// packages/comment-angular/src/lib/comment-content.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import type { CommentMentionSummary } from '@nabarun-ngo/comment-core';
import { parseContentSegments } from '@nabarun-ngo/comment-core';

@Component({
  selector: 'cm-comment-content',
  standalone: true,
  template: `
    @for (segment of segments; track $index) {
      @if (segment.type === 'mention') {
        <strong [attr.data-mention-id]="segment.userId">{{ segment.text }}</strong>
      } @else {
        <span>{{ segment.text }}</span>
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommentContentComponent {
  @Input({ required: true }) content!: string;
  @Input() mentions: CommentMentionSummary[] = [];

  get segments() {
    return parseContentSegments(this.content, this.mentions);
  }
}

// packages/comment-react/src/CommentContent.tsx
import type { CommentMentionSummary } from '@nabarun-ngo/comment-core';
import { parseContentSegments } from '@nabarun-ngo/comment-core';

export interface CommentContentClassNames {
  root?: string;
  mention?: string;
}

export interface CommentContentProps {
  content: string;
  mentions?: CommentMentionSummary[];
  classNames?: CommentContentClassNames;
}

export function CommentContent({ content, mentions = [], classNames }: CommentContentProps) {
  const segments = parseContentSegments(content, mentions);

  return (
    <span className={classNames?.root}>
      {segments.map((segment, index) =>
        segment.type === 'mention' ? (
          <strong key={index} className={classNames?.mention} data-mention-id={segment.userId}>
            {segment.text}
          </strong>
        ) : (
          <span key={index}>{segment.text}</span>
        ),
      )}
    </span>
  );
}
