// packages/comment-angular/src/lib/mention-comment-editor.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  forwardRef,
  Inject,
  Input,
  Optional,
  ViewChild,
} from '@angular/core';
import {
  ControlValueAccessor,
  FormsModule,
  NG_VALUE_ACCESSOR,
} from '@angular/forms';
import type { CommentEditorValue, MentionCandidate } from '@nabarun-ngo/comment-core';
import {
  buildCommentEditorValue,
  contentToEditableText,
  deduplicateMentions,
  getActiveMentionQuery,
  insertMentionInEditableText,
} from '@nabarun-ngo/comment-core';
import { CommentContentComponent } from './comment-content.component';
import { MENTION_USER_SEARCH, type MentionUserSearchFn } from './tokens';

@Component({
  selector: 'cm-mention-comment-editor',
  standalone: true,
  imports: [FormsModule, CommentContentComponent],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MentionCommentEditorComponent),
      multi: true,
    },
  ],
  template: `
    <div class="cm-mention-editor">
      <textarea
        #textarea
        [rows]="rows"
        [placeholder]="placeholder"
        [disabled]="disabled"
        [(ngModel)]="editableText"
        (ngModelChange)="onEditableChange($event)"
        (click)="syncCursor()"
        (keyup)="syncCursor()"
        (keydown)="onKeyDown($event)"
      ></textarea>

      @if (mentionOpen) {
        <ul class="cm-mention-list" role="listbox">
          @if (loading) {
            <li>Searching…</li>
          } @else if (candidates.length === 0) {
            <li>No people found</li>
          } @else {
            @for (candidate of candidates; track candidate.userId; let i = $index) {
              <li
                role="option"
                [class.active]="i === activeIndex"
                (mousedown)="pickCandidate(candidate, $event)"
              >
                {{ candidate.displayName }}
                @if (candidate.email) {
                  <span>{{ candidate.email }}</span>
                }
              </li>
            }
          }
        </ul>
      }

      @if (showPreview && value) {
        <cm-comment-content [content]="value.content" [mentions]="value.mentions" />
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MentionCommentEditorComponent implements ControlValueAccessor {
  @Input() rows = 4;
  @Input() placeholder = 'Write a comment… Use @ to mention someone';
  @Input() minMentionQueryLength = 1;
  @Input() showPreview = false;
  @Input() debounceMs = 200;
  @Input() searchUsers?: MentionUserSearchFn;

  @ViewChild('textarea') textareaRef?: ElementRef<HTMLTextAreaElement>;

  value: CommentEditorValue = { content: '', mentions: [] };
  editableText = '';
  disabled = false;

  mentionOpen = false;
  loading = false;
  candidates: MentionCandidate[] = [];
  activeIndex = 0;
  private cursor = 0;
  private mentionList: MentionCandidate[] = [];
  private searchTimer?: ReturnType<typeof setTimeout>;
  private requestId = 0;

  private onChange: (value: CommentEditorValue) => void = () => undefined;
  private onTouched: () => void = () => undefined;

  constructor(
    private readonly cdr: ChangeDetectorRef,
    @Optional() @Inject(MENTION_USER_SEARCH) private readonly injectedSearch?: MentionUserSearchFn,
  ) {}

  private resolveSearch(): MentionUserSearchFn | undefined {
    return this.searchUsers ?? this.injectedSearch;
  }

  writeValue(value: CommentEditorValue | null): void {
    this.value = value ?? { content: '', mentions: [] };
    this.mentionList = [...this.value.mentions];
    this.editableText = contentToEditableText(this.value.content, this.value.mentions);
    this.cdr.markForCheck();
  }

  registerOnChange(fn: (value: CommentEditorValue) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
    this.cdr.markForCheck();
  }

  onEditableChange(nextEditable: string): void {
    this.editableText = nextEditable;
    this.value = buildCommentEditorValue(nextEditable, this.mentionList);
    this.mentionList = [...this.value.mentions];
    this.onChange(this.value);
    this.scheduleSearch();
    this.cdr.markForCheck();
  }

  syncCursor(): void {
    const el = this.textareaRef?.nativeElement;
    this.cursor = el?.selectionStart ?? this.editableText.length;
    this.scheduleSearch();
  }

  onKeyDown(event: KeyboardEvent): void {
    if (!this.mentionOpen || this.candidates.length === 0) {
      return;
    }

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      this.activeIndex = (this.activeIndex + 1) % this.candidates.length;
      return;
    }

    if (event.key === 'ArrowUp') {
      event.preventDefault();
      this.activeIndex =
        (this.activeIndex - 1 + this.candidates.length) % this.candidates.length;
      return;
    }

    if (event.key === 'Enter' || event.key === 'Tab') {
      event.preventDefault();
      const candidate = this.candidates[this.activeIndex];
      if (candidate) {
        this.applyCandidate(candidate);
      }
      return;
    }

    if (event.key === 'Escape') {
      event.preventDefault();
      this.candidates = [];
      this.mentionOpen = false;
    }
  }

  pickCandidate(candidate: MentionCandidate, event: MouseEvent): void {
    event.preventDefault();
    this.applyCandidate(candidate);
  }

  private applyCandidate(candidate: MentionCandidate): void {
    const result = insertMentionInEditableText(this.editableText, this.cursor, candidate);
    this.mentionList = deduplicateMentions([
      ...this.mentionList.filter((m) => m.userId !== candidate.userId),
      candidate,
    ]);
    this.editableText = result.text;
    this.cursor = result.cursor;
    this.value = buildCommentEditorValue(this.editableText, this.mentionList);
    this.onChange(this.value);
    this.candidates = [];
    this.mentionOpen = false;

    queueMicrotask(() => {
      const el = this.textareaRef?.nativeElement;
      if (!el) return;
      el.focus();
      el.setSelectionRange(this.cursor, this.cursor);
    });

    this.cdr.markForCheck();
  }

  private scheduleSearch(): void {
    const searchUsers = this.resolveSearch();
    if (!searchUsers) {
      this.mentionOpen = false;
      return;
    }

    const query = getActiveMentionQuery(this.editableText, this.cursor);
    if (query === null || query.length < this.minMentionQueryLength) {
      this.mentionOpen = query !== null;
      this.candidates = [];
      this.loading = false;
      this.cdr.markForCheck();
      return;
    }

    this.mentionOpen = true;
    this.loading = true;
    const requestId = ++this.requestId;

    if (this.searchTimer) {
      clearTimeout(this.searchTimer);
    }

    this.searchTimer = setTimeout(() => {
      void Promise.resolve(searchUsers(query))
        .then((results) => {
          if (requestId !== this.requestId) return;
          this.candidates = results;
          this.activeIndex = 0;
        })
        .finally(() => {
          if (requestId === this.requestId) {
            this.loading = false;
            this.cdr.markForCheck();
          }
        });
    }, this.debounceMs);
  }
}

// packages/comment-react/src/MentionCommentEditor.tsx
import {
  useCallback,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type KeyboardEvent,
  type MouseEvent,
  type TextareaHTMLAttributes,
} from 'react';
import type { CommentEditorValue, MentionCandidate, MentionUserSearch } from '@nabarun-ngo/comment-core';
import {
  buildCommentEditorValue,
  contentToEditableText,
  deduplicateMentions,
  insertMentionInEditableText,
} from '@nabarun-ngo/comment-core';
import { CommentContent } from './CommentContent.js';
import { syncTextareaCursor, useMentionAutocomplete } from './useMentionAutocomplete.js';

export interface MentionCommentEditorClassNames {
  root?: string;
  textarea?: string;
  mentionList?: string;
  mentionOption?: string;
  mentionOptionActive?: string;
  preview?: string;
}

export interface MentionCommentEditorProps
  extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'value' | 'onChange' | 'defaultValue'> {
  value: CommentEditorValue;
  onChange: (value: CommentEditorValue) => void;
  searchUsers: MentionUserSearch;
  minMentionQueryLength?: number;
  showPreview?: boolean;
  classNames?: MentionCommentEditorClassNames;
  mentionListLabel?: string;
}

export function MentionCommentEditor({
  value,
  onChange,
  searchUsers,
  minMentionQueryLength = 1,
  showPreview = false,
  classNames,
  mentionListLabel = 'Mention suggestions',
  placeholder = 'Write a comment… Use @ to mention someone',
  rows = 4,
  ...textareaProps
}: MentionCommentEditorProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [cursor, setCursor] = useState(0);

  const editableText = contentToEditableText(value.content, value.mentions);

  const emitFromEditable = useCallback(
    (nextEditable: string, mentionList = value.mentions) => {
      onChange(buildCommentEditorValue(nextEditable, mentionList));
    },
    [onChange, value.mentions],
  );

  const onMentionSelect = useCallback(
    (candidate: MentionCandidate) => {
      const result = insertMentionInEditableText(editableText, cursor, candidate);
      const nextMentions = deduplicateMentions([
        ...value.mentions.filter((m) => m.userId !== candidate.userId),
        candidate,
      ]);
      onChange(buildCommentEditorValue(result.text, nextMentions));
      setCursor(result.cursor);
      syncTextareaCursor(textareaRef, result.cursor);
    },
    [cursor, editableText, onChange, value.mentions],
  );

  const autocomplete = useMentionAutocomplete(
    {
      editableText,
      cursor,
      searchUsers,
      minQueryLength: minMentionQueryLength,
    },
    onMentionSelect,
  );

  const onTextChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    const next = event.target.value;
    const nextCursor = event.target.selectionStart ?? next.length;
    setCursor(nextCursor);
    emitFromEditable(next);
  };

  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (autocomplete.handleKeyDown(event)) {
      return;
    }
    textareaProps.onKeyDown?.(event);
  };

  const onSelect = (event: ChangeEvent<HTMLTextAreaElement>) => {
    setCursor(event.target.selectionStart ?? 0);
    textareaProps.onSelect?.(event);
  };

  const onClick = (event: MouseEvent<HTMLTextAreaElement>) => {
    const target = event.currentTarget;
    setCursor(target.selectionStart ?? 0);
    textareaProps.onClick?.(event);
  };

  const previewMentions = useMemo(
    () => value.mentions.map((m) => ({ userId: m.userId, displayName: m.displayName })),
    [value.mentions],
  );

  return (
    <div className={classNames?.root} data-mention-editor>
      <textarea
        {...textareaProps}
        ref={textareaRef}
        className={classNames?.textarea}
        value={editableText}
        rows={rows}
        placeholder={placeholder}
        aria-autocomplete="list"
        aria-controls={autocomplete.open ? autocomplete.listboxId : undefined}
        aria-expanded={autocomplete.open}
        onChange={onTextChange}
        onKeyDown={onKeyDown}
        onSelect={onSelect}
        onClick={onClick}
      />

      {autocomplete.open ? (
        <ul
          id={autocomplete.listboxId}
          className={classNames?.mentionList}
          role="listbox"
          aria-label={mentionListLabel}
        >
          {autocomplete.loading ? (
            <li role="option" aria-disabled="true">
              Searching…
            </li>
          ) : null}
          {!autocomplete.loading && autocomplete.candidates.length === 0 ? (
            <li role="option" aria-disabled="true">
              No people found
            </li>
          ) : null}
          {autocomplete.candidates.map((candidate, index) => {
            const active = index === autocomplete.activeIndex;
            return (
              <li
                key={candidate.userId}
                role="option"
                aria-selected={active}
                className={
                  active
                    ? [classNames?.mentionOption, classNames?.mentionOptionActive]
                        .filter(Boolean)
                        .join(' ')
                    : classNames?.mentionOption
                }
                onMouseDown={(event) => {
                  event.preventDefault();
                  autocomplete.selectCandidate(candidate);
                }}
                onMouseEnter={() => autocomplete.setActiveIndex(index)}
              >
                <span>{candidate.displayName}</span>
                {candidate.email ? <span>{candidate.email}</span> : null}
              </li>
            );
          })}
        </ul>
      ) : null}

      {showPreview ? (
        <div className={classNames?.preview} aria-live="polite">
          <CommentContent content={value.content} mentions={previewMentions} />
        </div>
      ) : null}
    </div>
  );
}

export { CommentContent } from './CommentContent.js';
export type { CommentContentClassNames, CommentContentProps } from './CommentContent.js';
